### ISSUE TITLE
Installing Gem via VS Remote Code causes: NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by raouldevil** [teamsimplepay/ooxml_crypt#1]
With this Gem in the Gemfile, when I try to run `bundle install` in a VS Remote Container using Docker I get this error:

```
Fetching ooxml_crypt 0.1.0
Installing ooxml_crypt 0.1.0 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `full_name' for nil:NilClass
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:123:in `each'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:122:in `each'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:100:in `call'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:71:in `call'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer.rb:262:in `install_in_parallel'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer.rb:209:in `install'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer.rb:89:in `block in run'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer.rb:71:in `run'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/installer.rb:23:in `install'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/install.rb:60:in `run'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:253:in `block in install'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:252:in `install'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
  /usr/local/bundle/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/bundle/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
  /usr/local/bundle/bin/bundle:23:in `load'
  /usr/local/bundle/bin/bundle:23:in `<main>'
```

**Comment by ashkulz** [comment]
@raouldevil looks like a bundler issue due to sorbet, see rubygems/rubygems#5088. Can you try using the latest bundler release?
